### ISSUE TITLE
ConfigForAny and ConfigForPeer create tls.Config that can not be reused

### ISSUE THREAD

**Issue by xiegeo** [libp2p/go-libp2p-tls#35]
When the conf.VerifyPeerCertificate is called a second time, such as when accepting connections. It will attempt to send on a closed channel. Is this a bug or I'm I misusing the API?

**Comment by raulk** [comment]
@marten-seemann – could you have a look at this? Should this function be idempotent?

**Comment by marten-seemann** [comment]
These configs are only supposed to be used a single time. There shouldn't be any need to use these configs anyway, the only reason we're exposing them is to use them in the QUIC handshake.

**Comment by bonedaddy** [comment]
@marten-seemann what's the reasoning for not allowing re-use of them? I can certainly imagine scenarios in which you want to re-use the configs, say if you're connecting to a service of a libp2p node that will also use its peerID for the tls connection.

Additionally if you want to use `go-libp2p-tls` as an actual TLS transport between hosts it is unable to do this, because you can't re-use configs.

This transport has uses outside of being used in the QUIC handshake, but with configs that can only be used a single time, it can't be used.

**Comment by marten-seemann** [comment]
As I said, these configs are **only** exposed for usage in the QUIC handshake. They shouldn't be used for anything else.
If there was a way to make the private for all users but go-libp2p-quic-transport, we'd do that. Unfortunately, Go doesn't allow us to do that.
